/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventry_mangement_system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinuwan Theekshana
 */
public class JFrame_8 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_8
     */
    public JFrame_8() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        javax.swing.border.Border JPanel_title__Border = BorderFactory.createMatteBorder(7, 7, 7, 7, Color.black);
        jPanel1.setBorder(JPanel_title__Border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel_Val_ID = new javax.swing.JLabel();
        jButton_Clr = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_Back1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remove your user account");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/inventry_mangement_system/Actions-list-remove-user-icon-1.png"))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Remove the User Account");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 590, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("V");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(410, 170, 20, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ID :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 180, 80, 22);

        jTextField_ID.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jTextField_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_IDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_ID);
        jTextField_ID.setBounds(180, 170, 250, 30);

        jLabel_Val_ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Val_ID.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_ID);
        jLabel_Val_ID.setBounds(180, 220, 250, 30);

        jButton_Clr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Clr.setText("Clear");
        jButton_Clr.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_Clr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClrActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Clr);
        jButton_Clr.setBounds(460, 300, 120, 40);

        jButton_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Delete);
        jButton_Delete.setBounds(260, 300, 120, 40);

        jButton_Back1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Back1.setText("<<Back");
        jButton_Back1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_Back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Back1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back1);
        jButton_Back1.setBounds(40, 300, 120, 40);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 590, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_IDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDKeyReleased
        jLabel_Val_ID.setText("");
    }//GEN-LAST:event_jTextField_IDKeyReleased

    private void jTextField_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDKeyTyped

        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {

            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTextField_IDKeyTyped

    private void jButton_ClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClrActionPerformed

        jTextField_ID.setText(null);
        jLabel_Val_ID.setText(null);
        jTextField_ID.grabFocus();

    }//GEN-LAST:event_jButton_ClrActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed

        if (jTextField_ID.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter the your N.I.C Number before delete data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "inventry_management_system";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                int a;
                a = JOptionPane.showConfirmDialog(null, "Are you sure to you went delete that user in databasse", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

                if (a == 0) {

                    String query = "DELETE FROM user WHERE ID=?";

                    PreparedStatement pst = con.prepareStatement(query);

                    pst.setString(1, jTextField_ID.getText());
                    pst.executeUpdate();

                    jTextField_ID.setText(null);
                    jLabel_Val_ID.setText(null);
                    jTextField_ID.grabFocus();;

                    System.out.println(pst);
                    System.out.println("1 row affected");

                    JOptionPane.showMessageDialog(null, "Record Deleted Succsessftlly...");

                }
                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_8.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

                jTextField_ID.setText(null);
                jLabel_Val_ID.setText(null);
                jTextField_ID.grabFocus();
            }

        }

    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Back1ActionPerformed

        JFrame_6 f6 = new JFrame_6();
        f6.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton_Back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back1;
    private javax.swing.JButton jButton_Clr;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Val_ID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_ID;
    // End of variables declaration//GEN-END:variables
}
