/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventry_mangement_system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.BorderFactory;

/**
 *
 * @author Dinuwan Theekshana
 */
public class JFrame_6 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_6
     */
    public JFrame_6() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        javax.swing.border.Border JPanel_title__Border = BorderFactory.createMatteBorder(7, 7, 7, 7, Color.black);
        jPanel1.setBorder(JPanel_title__Border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_User_Control1 = new javax.swing.JButton();
        jButton_Remove_User = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Account Control");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/inventry_mangement_system/Users-icon.png"))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jButton_User_Control1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_User_Control1.setIcon(new javax.swing.ImageIcon("E:\\My Java Projects\\Inventry_Mangement_System\\Icons\\edit-validated-icon.png")); // NOI18N
        jButton_User_Control1.setText("Update Your Account");
        jButton_User_Control1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_User_Control1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_User_Control1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_User_Control1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_User_Control1);
        jButton_User_Control1.setBounds(140, 250, 270, 60);

        jButton_Remove_User.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Remove_User.setIcon(new javax.swing.ImageIcon("E:\\My Java Projects\\Inventry_Mangement_System\\Icons\\Actions-list-remove-user-icon-1.png")); // NOI18N
        jButton_Remove_User.setText("Remove Account");
        jButton_Remove_User.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_Remove_User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_UserActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Remove_User);
        jButton_Remove_User.setBounds(140, 330, 270, 60);

        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Back.setIcon(new javax.swing.ImageIcon("E:\\My Java Projects\\Inventry_Mangement_System\\Icons\\arrow-back-icon.png")); // NOI18N
        jButton_Back.setText("<<Back");
        jButton_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back);
        jButton_Back.setBounds(140, 410, 270, 60);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Account Control");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 50, 540, 33);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 90, 190, 150);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 530, 516);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_User_Control1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_User_Control1ActionPerformed

        JFrame_7 f7 = new JFrame_7();
        f7.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton_User_Control1ActionPerformed

    private void jButton_Remove_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_UserActionPerformed

        JFrame_8 f8 = new JFrame_8();
        f8.setVisible(true);

    }//GEN-LAST:event_jButton_Remove_UserActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed

        JFrame_5 f5 = new JFrame_5();
        f5.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Remove_User;
    private javax.swing.JButton jButton_User_Control1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
