/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventry_mangement_system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinuwan Theekshana
 */
public class JFrame_3 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_3
     */
    public JFrame_3() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        javax.swing.border.Border JPanel_title__Border = BorderFactory.createMatteBorder(7, 7, 7, 7, Color.black);
        jPanel1.setBorder(JPanel_title__Border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel_Val_ID = new javax.swing.JLabel();
        jPassword_New_pw = new javax.swing.JPasswordField();
        jLabel_Val_New_pw = new javax.swing.JLabel();
        jPassword_Conform_PW = new javax.swing.JPasswordField();
        jLabel_Val_Confirm_pw = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_Back = new javax.swing.JButton();
        jButton_Forgot = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forgot My Password");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/inventry_mangement_system/icons8-password-reset-30.png"))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Forgot My Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 30, 590, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("V");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(530, 140, 20, 30);

        jTextField_ID.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jTextField_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_IDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_ID);
        jTextField_ID.setBounds(270, 140, 280, 30);

        jLabel_Val_ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Val_ID.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_ID);
        jLabel_Val_ID.setBounds(270, 180, 280, 30);

        jPassword_New_pw.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPassword_New_pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPassword_New_pwKeyReleased(evt);
            }
        });
        jPanel1.add(jPassword_New_pw);
        jPassword_New_pw.setBounds(270, 210, 280, 30);

        jLabel_Val_New_pw.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Val_New_pw.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_New_pw);
        jLabel_Val_New_pw.setBounds(280, 250, 270, 30);

        jPassword_Conform_PW.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPassword_Conform_PW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPassword_Conform_PWKeyReleased(evt);
            }
        });
        jPanel1.add(jPassword_Conform_PW);
        jPassword_Conform_PW.setBounds(270, 280, 280, 30);

        jLabel_Val_Confirm_pw.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Val_Confirm_pw.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_Confirm_pw);
        jLabel_Val_Confirm_pw.setBounds(270, 320, 280, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Conform Password :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 280, 190, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("New Password :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 210, 160, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("ID :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 140, 100, 20);

        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Back.setText("<<Back");
        jButton_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back);
        jButton_Back.setBounds(30, 370, 140, 40);

        jButton_Forgot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Forgot.setText("Forgot");
        jButton_Forgot.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_Forgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Forgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ForgotActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Forgot);
        jButton_Forgot.setBounds(230, 370, 140, 40);

        jButton_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Clear.setText("Clear");
        jButton_Clear.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Clear);
        jButton_Clear.setBounds(430, 370, 140, 40);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_IDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDKeyReleased
        jLabel_Val_ID.setText("");
    }//GEN-LAST:event_jTextField_IDKeyReleased

    private void jTextField_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDKeyTyped

        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {

            evt.consume();
            getToolkit().beep();
        }

    }//GEN-LAST:event_jTextField_IDKeyTyped

    private void jPassword_New_pwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword_New_pwKeyReleased
        jLabel_Val_New_pw.setText("");
    }//GEN-LAST:event_jPassword_New_pwKeyReleased

    private void jPassword_Conform_PWKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword_Conform_PWKeyReleased
        jLabel_Val_Confirm_pw.setText("");
    }//GEN-LAST:event_jPassword_Conform_PWKeyReleased

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_ForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ForgotActionPerformed

        if (jTextField_ID.getText().trim().isEmpty() && jPassword_Conform_PW.getText().trim().isEmpty() && jPassword_New_pw.getText().trim().isEmpty()) {

            jLabel_Val_Confirm_pw.setText("Conform your password.");
            jLabel_Val_ID.setText("N.I.C Number is empty");
            jLabel_Val_New_pw.setText("Enter your new password.");

        } else if (jTextField_ID.getText().trim().isEmpty()) {

            jLabel_Val_ID.setText("N.I.C Number is empty");

        } else if (jPassword_Conform_PW.getText().trim().isEmpty()) {

            jLabel_Val_Confirm_pw.setText("Conform your password.");

        } else if (jPassword_New_pw.getText().trim().isEmpty()) {

            jLabel_Val_New_pw.setText("Enter your new password.");

        } else if (!jPassword_New_pw.getText().equals(jPassword_Conform_PW.getText())) {

            JOptionPane.showMessageDialog(null, "Password is not matched", "Messege", JOptionPane.WARNING_MESSAGE);

            jPassword_Conform_PW.setText(null);
            jPassword_New_pw.setText(null);
            jTextField_ID.setText(null);
            jTextField_ID.grabFocus();

        } else {

            JOptionPane.showMessageDialog(null, "Password is matched");

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "inventry_management_system";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "UPDATE user SET Password=? ,Re_Enter_Password=? WHERE ID=?";//query wka ewnass wenawa ekinekata

                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, jPassword_New_pw.getText());//query eke adala feild eka yedi athi place eke number eka merhanadi parameeeter eka lesa yediya yuthuya.
                pst.setString(2, jPassword_Conform_PW.getText());
                pst.setString(3, jTextField_ID.getText());
                pst.executeUpdate();

                System.out.println(pst);
                System.out.println("1 row affected");

                JOptionPane.showMessageDialog(null, "Your Password is forgot.");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_4.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

            }
            jPassword_Conform_PW.setText(null);
            jPassword_New_pw.setText(null);
            jTextField_ID.setText(null);
            jTextField_ID.grabFocus();

        }

    }//GEN-LAST:event_jButton_ForgotActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed

        jPassword_Conform_PW.setText(null);
        jTextField_ID.setText(null);
        jPassword_New_pw.setText(null);
        jLabel_Val_Confirm_pw.setText(null);
        jLabel_Val_ID.setText(null);
        jLabel_Val_New_pw.setText(null);
        jTextField_ID.grabFocus();

    }//GEN-LAST:event_jButton_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Forgot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Val_Confirm_pw;
    private javax.swing.JLabel jLabel_Val_ID;
    private javax.swing.JLabel jLabel_Val_New_pw;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword_Conform_PW;
    private javax.swing.JPasswordField jPassword_New_pw;
    private javax.swing.JTextField jTextField_ID;
    // End of variables declaration//GEN-END:variables
}
