/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventry_mangement_system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dinuwan Theekshana
 */
public class JFrame_9 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_9
     */
    public JFrame_9() {
        initComponents();
        showTableData();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        
        javax.swing.border.Border JPanel_title__Border = BorderFactory.createMatteBorder(7, 7, 7, 7, Color.black);
        jPanel1.setBorder(JPanel_title__Border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Serial_Num = new javax.swing.JTextField();
        jTextField_Model = new javax.swing.JTextField();
        jTextField_Aset_number = new javax.swing.JTextField();
        jTextField_WKS = new javax.swing.JTextField();
        jTextField_IP = new javax.swing.JTextField();
        jLabel_Val_Serial = new javax.swing.JLabel();
        jLabel_Val_model = new javax.swing.JLabel();
        jLabel_Val_Aset = new javax.swing.JLabel();
        jLabel_Val_WKS = new javax.swing.JLabel();
        jLabel_Val_IP = new javax.swing.JLabel();
        jButton_Back = new javax.swing.JButton();
        jButton_Add = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Serch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Details of the system units");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Details of the system units");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 990, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Serial Number :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 130, 150, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Model :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 210, 90, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Aset Number :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 300, 140, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("WKS :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 390, 90, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("IP :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 480, 90, 22);

        jTextField_Serial_Num.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Serial_Num);
        jTextField_Serial_Num.setBounds(210, 120, 220, 30);

        jTextField_Model.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Model);
        jTextField_Model.setBounds(210, 200, 220, 30);

        jTextField_Aset_number.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Aset_number);
        jTextField_Aset_number.setBounds(210, 290, 220, 30);

        jTextField_WKS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_WKS);
        jTextField_WKS.setBounds(210, 380, 220, 30);

        jTextField_IP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_IP);
        jTextField_IP.setBounds(210, 470, 220, 30);

        jLabel_Val_Serial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Val_Serial.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_Serial);
        jLabel_Val_Serial.setBounds(210, 160, 220, 30);

        jLabel_Val_model.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Val_model.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_model);
        jLabel_Val_model.setBounds(210, 240, 220, 30);

        jLabel_Val_Aset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Val_Aset.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_Aset);
        jLabel_Val_Aset.setBounds(210, 330, 220, 30);

        jLabel_Val_WKS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Val_WKS.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_WKS);
        jLabel_Val_WKS.setBounds(210, 420, 220, 30);

        jLabel_Val_IP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Val_IP.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_IP);
        jLabel_Val_IP.setBounds(210, 510, 220, 30);

        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Back.setText("<<Back");
        jButton_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back);
        jButton_Back.setBounds(30, 570, 120, 40);

        jButton_Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Add.setText("Add");
        jButton_Add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Add);
        jButton_Add.setBounds(220, 570, 120, 40);

        jButton_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Delete);
        jButton_Delete.setBounds(430, 570, 120, 40);

        jButton_Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Update.setText("Update");
        jButton_Update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Update);
        jButton_Update.setBounds(640, 570, 120, 40);

        jButton_Serch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Serch.setText("Search");
        jButton_Serch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Serch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Serch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SerchActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Serch);
        jButton_Serch.setBounds(860, 570, 120, 40);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(470, 120, 510, 380);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 1000, 630);

        jMenu3.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Print");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        
        JFrame_5 f5 = new JFrame_5();
        f5.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        
        if (jTextField_Serial_Num.getText().trim().isEmpty() && jTextField_Model.getText().trim().isEmpty() && jTextField_Aset_number.getText().trim().isEmpty() && jTextField_WKS.getText().trim().isEmpty() && jTextField_IP.getText().trim().isEmpty()) {
            
            jLabel_Val_Serial.setText("input the serial number.");
            jLabel_Val_model.setText("input the modle.");
            jLabel_Val_Aset.setText("Input the Asset number.");
            jLabel_Val_WKS.setText("Input the WKS.");
            jLabel_Val_IP.setText("Input the IP.");
            getToolkit().beep();
            
        } else if (jTextField_Serial_Num.getText().trim().isEmpty()) {
            
            jLabel_Val_Serial.setText("input the serial number.");
            getToolkit().beep();
            
        } else if (jTextField_Model.getText().trim().isEmpty()) {
            
            jLabel_Val_model.setText("input the modle.");
            getToolkit().beep();
            
        } else if (jTextField_Aset_number.getText().trim().isEmpty()) {
            
            jLabel_Val_Aset.setText("Input the Asset number.");
            getToolkit().beep();
            
        } else if (jTextField_WKS.getText().trim().isEmpty()) {
            
            jLabel_Val_WKS.setText("Input the WKS.");
            getToolkit().beep();
            
        } else if (jTextField_IP.getText().trim().isEmpty()) {
            
            jLabel_Val_IP.setText("Input the IP.");
            getToolkit().beep();
            
        } else {
            
            try {
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "inventry_management_system";
                String user = "root";
                String pword = "123456";
                
                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);
                
                String query = "INSERT INTO details_of_system_unit (Serial_Number, Model, Aset_Number, WKS, IP) VALUES (?,?,?,?,?)";
                
                PreparedStatement pst = con.prepareStatement(query);
                
                pst.setString(1, jTextField_Serial_Num.getText());//query eke adala feild eka yedi athi place eke number eka merhanadi parameeeter eka lesa yediya yuthuya.
                pst.setString(2, jTextField_Model.getText());
                pst.setString(3, jTextField_Aset_number.getText());
                pst.setString(4, jTextField_WKS.getText());
                pst.setString(5, jTextField_IP.getText());
                
                pst.executeUpdate();
                
                System.out.println(pst);
                System.out.println("1 row affected");
                
                JOptionPane.showMessageDialog(null, "Data Inserted Succsessfully!!!");
                
                con.close();
                
                jTextField_Aset_number.setText(null);
                jTextField_IP.setText(null);
                jTextField_Model.setText(null);
                jTextField_Serial_Num.setText(null);
                jTextField_WKS.setText(null);
                jLabel_Val_Aset.setText(null);
                jLabel_Val_IP.setText(null);
                jLabel_Val_Serial.setText(null);
                jLabel_Val_WKS.setText(null);
                jLabel_Val_model.setText(null);
                jTextField_Serial_Num.grabFocus();
                
            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
                
                Logger.getLogger(JFrame_9.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
                
                jTextField_Aset_number.setText(null);
                jTextField_IP.setText(null);
                jTextField_Model.setText(null);
                jTextField_Serial_Num.setText(null);
                jTextField_WKS.setText(null);
                jLabel_Val_Aset.setText(null);
                jLabel_Val_IP.setText(null);
                jLabel_Val_Serial.setText(null);
                jLabel_Val_WKS.setText(null);
                jLabel_Val_model.setText(null);
                jTextField_Serial_Num.grabFocus();
                
            }
        }
        
        showTableData();
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int rows = jTable1.getRowCount();
        
        if (rows != 0) {
            
            int row_selected = jTable1.getSelectedRow();
            
            String serial = jTable1.getValueAt(row_selected, 0).toString();
            String model = jTable1.getValueAt(row_selected, 1).toString();
            String asset = jTable1.getValueAt(row_selected, 2).toString();
            String wks = jTable1.getValueAt(row_selected, 3).toString();
            String ip = jTable1.getValueAt(row_selected, 4).toString();
            
            jTextField_Serial_Num.setText(serial);
            jTextField_Model.setText(model);
            jTextField_Aset_number.setText(asset);
            jTextField_WKS.setText(wks);
            jTextField_IP.setText(ip);
            
        } else {
            
            JOptionPane.showMessageDialog(null, rows);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        jTextField_Aset_number.setText(null);
        jTextField_IP.setText(null);
        jTextField_Model.setText(null);
        jTextField_Serial_Num.setText(null);
        jTextField_WKS.setText(null);
        jLabel_Val_Aset.setText(null);
        jLabel_Val_IP.setText(null);
        jLabel_Val_Serial.setText(null);
        jLabel_Val_WKS.setText(null);
        jLabel_Val_model.setText(null);
        jTextField_Serial_Num.grabFocus();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        
        if (jTextField_Serial_Num.getText().trim().isEmpty() && jTextField_Aset_number.getText().trim().isEmpty()) {
            
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You should enter the serial number or asset number.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);
            
        } else {
            
            try {
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "inventry_management_system";
                String user = "root";
                String pword = "123456";
                
                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);
                
                int a;
                a = JOptionPane.showConfirmDialog(null, "Are you sure to you went delete that record in databasse", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                
                if (a == 0) {
                    
                    String query1 = "DELETE FROM details_of_system_unit WHERE Serial_Number=?";
                    
                    PreparedStatement pst1 = con.prepareStatement(query1);
                    
                    pst1.setString(1, jTextField_Serial_Num.getText());
                    pst1.executeUpdate();
                    System.out.println(pst1);
                    
                    String query2 = "DELETE FROM details_of_system_unit WHERE Aset_Number=?";
                    
                    PreparedStatement pst2 = con.prepareStatement(query2);
                    
                    pst2.setString(1, jTextField_Aset_number.getText());
                    pst2.executeUpdate();
                    System.out.println(pst2);
                    
                    jTextField_Aset_number.setText(null);
                    jTextField_IP.setText(null);
                    jTextField_Model.setText(null);
                    jTextField_Serial_Num.setText(null);
                    jTextField_WKS.setText(null);
                    jLabel_Val_Aset.setText(null);
                    jLabel_Val_IP.setText(null);
                    jLabel_Val_Serial.setText(null);
                    jLabel_Val_WKS.setText(null);
                    jLabel_Val_model.setText(null);
                    jTextField_Serial_Num.grabFocus();
                    
                    System.out.println("1 row affected");
                    
                    JOptionPane.showMessageDialog(null, "Record Deleted Succsessftlly...");
                    
                }
                con.close();
                
            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
                
                Logger.getLogger(JFrame_9.class.getName()).log(Level.SEVERE, null, ex);
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, ex);
                
                jTextField_Serial_Num.setText(null);
                jTextField_Aset_number.setText(null);
                jTextField_Serial_Num.grabFocus();
            }
            
        }
        showTableData();
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        
        if (jTextField_Serial_Num.getText().trim().isEmpty() && jTextField_Model.getText().trim().isEmpty() && jTextField_Aset_number.getText().trim().isEmpty() && jTextField_WKS.getText().trim().isEmpty() && jTextField_IP.getText().trim().isEmpty()) {
            
            jLabel_Val_Serial.setText("input the serial number.");
            jLabel_Val_model.setText("input the modle.");
            jLabel_Val_Aset.setText("Input the Asset number.");
            jLabel_Val_WKS.setText("Input the WKS.");
            jLabel_Val_IP.setText("Input the IP.");
            getToolkit().beep();
            
        } else if (jTextField_Serial_Num.getText().trim().isEmpty()) {
            
            jLabel_Val_Serial.setText("input the serial number.");
            getToolkit().beep();
            
        } else if (jTextField_Model.getText().trim().isEmpty()) {
            
            jLabel_Val_model.setText("input the modle.");
            getToolkit().beep();
            
        } else if (jTextField_Aset_number.getText().trim().isEmpty()) {
            
            jLabel_Val_Aset.setText("Input the Asset number.");
            getToolkit().beep();
            
        } else if (jTextField_WKS.getText().trim().isEmpty()) {
            
            jLabel_Val_WKS.setText("Input the WKS.");
            getToolkit().beep();
            
        } else if (jTextField_IP.getText().trim().isEmpty()) {
            
            jLabel_Val_IP.setText("Input the IP.");
            getToolkit().beep();
            
        } else {
            
            try {
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "inventry_management_system";
                String user = "root";
                String pword = "123456";
                
                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);
                
                String query1 = "UPDATE details_of_system_unit SET Model=? ,Aset_Number=? ,WKS=?, IP=? WHERE Serial_Number=?";//query wka ewnass wenawa ekinekata

                PreparedStatement pst1 = con.prepareStatement(query1);
                
                pst1.setString(5, jTextField_Serial_Num.getText());//query eke adala feild eka yedi athi place eke number eka merhanadi parameeeter eka lesa yediya yuthuya.
                pst1.setString(1, jTextField_Model.getText());
                pst1.setString(2, jTextField_Aset_number.getText());
                pst1.setString(3, jTextField_WKS.getText());
                pst1.setString(4, jTextField_IP.getText());
                pst1.executeUpdate();
                System.out.println(query1);
                
                String query2 = "UPDATE details_of_system_unit SET Serial_Number=?, Model=? ,WKS=?, IP=? WHERE Aset_Number=?";
                
                PreparedStatement pst2 = con.prepareStatement(query2);
                
                pst2.setString(5, jTextField_Aset_number.getText());//query eke adala feild eka yedi athi place eke number eka merhanadi parameeeter eka lesa yediya yuthuya.
                pst2.setString(1, jTextField_Serial_Num.getText());
                pst2.setString(2, jTextField_Model.getText());
                pst2.setString(3, jTextField_WKS.getText());
                pst2.setString(4, jTextField_IP.getText());
                pst2.executeUpdate();
                System.out.println(query2);
                
                System.out.println("1 row affected");
                
                JOptionPane.showMessageDialog(null, "Data Updated Succsessfully!!!");
                
                con.close();
                
            } catch (ClassNotFoundException | SQLException ex) {
                
                Logger.getLogger(JFrame_9.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
                
            }
        }
        showTableData();
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_SerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SerchActionPerformed
        
        if (jTextField_Serial_Num.getText().trim().isEmpty() && jTextField_Aset_number.getText().trim().isEmpty()) {
            
            getToolkit().beep();
            
            JOptionPane.showMessageDialog(null, "You should enter the Serial Number  or Asset Number before Search data.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);
//
//        } else if (jTextField_Aset_number.getText().trim().isEmpty()){
//                
//        JOptionPane.showMessageDialog(null, "You should enter the Asset Number to before Search data.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);
//        
//        
        } else {
            
            try {
                String url = "jdbc:mysql://localhost:3306/"; //url
                String db = "inventry_management_system"; //Database Name
                String user = "root";//user name
                String pword = "123456"; //password

                System.out.println(jTextField_Serial_Num.getText());//search kirimata yoda gannna textbox eke variabale name eka.
                System.out.println(jTextField_Aset_number.getText());
                
                Connection con = null;
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance(); //driver
                con = DriverManager.getConnection(url + db, user, pword);

                //SQL Query
                String sql1 = "SELECT * FROM details_of_system_unit WHERE Serial_Number = '" + jTextField_Serial_Num.getText() + "'";
                
                ResultSet res1 = con.createStatement().executeQuery(sql1);
                System.out.println(sql1);
                
                while (res1.next()) {

                    /* System.out.println(res.getString("Patient_Name"));
                System.out.println(res.getString("Doctor_Name"));*/
                    jTextField_Model.setText(res1.getString("Model"));
                    jTextField_Aset_number.setText(res1.getString("Aset_Number"));
                    jTextField_WKS.setText(res1.getString("WKS"));
                    jTextField_IP.setText(res1.getString("IP"));//Text feild wala names ewa form eke athi piliwelata yodanna.

                    System.out.println(res1.getString("Model") + " " + res1.getString("Aset_Number"));
                    System.out.println("Row Affected");
                    //Vadagthma field deke names yodanna.

                }
                
                String sql2 = "SELECT * FROM details_of_system_unit WHERE Aset_Number = '" + jTextField_Aset_number.getText() + "'";
                
                ResultSet res2 = con.createStatement().executeQuery(sql2);
                System.out.println(sql2);
                
                while (res2.next()) {
                    
                    jTextField_Serial_Num.setText(res2.getString("Serial_Number"));
                    jTextField_Model.setText(res2.getString("Model"));
                    jTextField_Aset_number.setText(res2.getString("Aset_Number"));
                    jTextField_WKS.setText(res2.getString("WKS"));
                    jTextField_IP.setText(res2.getString("IP"));                    
                    
                    System.out.println(res2.getString("Model") + " " + res2.getString("Aset_Number"));
                    System.out.println("Row Affected");
                    
                }                
                
                con.close();//Connection eka close kirima.
            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {
                
                Logger.getLogger(JFrame_9.class.getName()).log(Level.SEVERE, null, ex);
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, ex);
                
                jTextField_Aset_number.setText(null);
                jTextField_IP.setText(null);
                jTextField_Model.setText(null);
                jTextField_Serial_Num.setText(null);
                jTextField_WKS.setText(null);
                jLabel_Val_Aset.setText(null);
                jLabel_Val_IP.setText(null);
                jLabel_Val_Serial.setText(null);
                jLabel_Val_WKS.setText(null);
                jLabel_Val_model.setText(null);
                jTextField_Serial_Num.grabFocus();
                
            }
            
        }
        showTableData();
    }//GEN-LAST:event_jButton_SerchActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
  
        JFrame_10 f10 = new JFrame_10();
        f10.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    public void showTableData() {
        
        try {
            
            String url = "jdbc:mysql://localhost:3306/";
            String db = "inventry_management_system";
            String user = "root";
            String pword = "123456";
            
            Connection con = null;
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            con = DriverManager.getConnection(url + db, user, pword);
            
            String query = "SELECT * FROM details_of_system_unit";
            
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet res = con.createStatement().executeQuery(query);
            
            pst = con.prepareStatement(query);
            res = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));
            
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {
            
            Logger.getLogger(JFrame_9.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    
    public void TextboxName(){
    
        jTextField_Serial_Num.getText();
        jTextField_Model.getText();
        jTextField_Aset_number.getText();
        jTextField_WKS.getText();
        jTextField_IP.getText();
            
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_9().setVisible(true);
            }
        });
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Serch;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Val_Aset;
    private javax.swing.JLabel jLabel_Val_IP;
    private javax.swing.JLabel jLabel_Val_Serial;
    private javax.swing.JLabel jLabel_Val_WKS;
    private javax.swing.JLabel jLabel_Val_model;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTextField jTextField_Aset_number;
    public static javax.swing.JTextField jTextField_IP;
    public static javax.swing.JTextField jTextField_Model;
    public static javax.swing.JTextField jTextField_Serial_Num;
    public static javax.swing.JTextField jTextField_WKS;
    // End of variables declaration//GEN-END:variables
}
