/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventry_mangement_system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Dinuwan Theekshana
 */
public class JFrame_7 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_7
     */
    public JFrame_7() {
        initComponents();
        initComponents();
        jLabel_Show_Password_dont_Delete.setVisible(false);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        javax.swing.border.Border JPanel_title__Border = BorderFactory.createMatteBorder(7, 7, 7, 7, Color.black);
        jPanel1.setBorder(JPanel_title__Border);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel_Ico_SHOW_Password = new javax.swing.JLabel();
        jLabel_Ico_SHOW_Retype_Password = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Val_ID = new javax.swing.JLabel();
        jTextField_Fname = new javax.swing.JTextField();
        jLabel_Val_FName = new javax.swing.JLabel();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Lname1 = new javax.swing.JTextField();
        jPasswordField_Re_Type_Pw = new javax.swing.JPasswordField();
        jButton_Close = new javax.swing.JButton();
        jButton_Clr1 = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jLabel_Val_Password = new javax.swing.JLabel();
        jLabel_Val_Retype_Psswd = new javax.swing.JLabel();
        jLabel_Val_LName = new javax.swing.JLabel();
        jLabel_Show_Password_dont_Delete = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update the user account");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/inventry_mangement_system/edit-validated-icon.png"))
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 7, true));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Update the user account");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 50, 880, 40);

        jTextField_ID.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jTextField_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_IDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_ID);
        jTextField_ID.setBounds(170, 140, 250, 30);

        jLabel_Ico_SHOW_Password.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Ico_SHOW_Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Ico_SHOW_Password.setIcon(new javax.swing.ImageIcon("E:\\My Java Projects\\Inventry_Mangement_System\\Icons\\icons8-eye-32.png")); // NOI18N
        jLabel_Ico_SHOW_Password.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jLabel_Ico_SHOW_Password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Ico_SHOW_Password.setOpaque(true);
        jLabel_Ico_SHOW_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Ico_SHOW_PasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Ico_SHOW_PasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Ico_SHOW_PasswordMouseExited(evt);
            }
        });
        jPanel1.add(jLabel_Ico_SHOW_Password);
        jLabel_Ico_SHOW_Password.setBounds(390, 290, 30, 30);

        jLabel_Ico_SHOW_Retype_Password.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Ico_SHOW_Retype_Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Ico_SHOW_Retype_Password.setIcon(new javax.swing.ImageIcon("E:\\My Java Projects\\Inventry_Mangement_System\\Icons\\icons8-eye-32.png")); // NOI18N
        jLabel_Ico_SHOW_Retype_Password.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jLabel_Ico_SHOW_Retype_Password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Ico_SHOW_Retype_Password.setOpaque(true);
        jLabel_Ico_SHOW_Retype_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Ico_SHOW_Retype_PasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Ico_SHOW_Retype_PasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Ico_SHOW_Retype_PasswordMouseExited(evt);
            }
        });
        jPanel1.add(jLabel_Ico_SHOW_Retype_Password);
        jLabel_Ico_SHOW_Retype_Password.setBounds(840, 290, 30, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ID :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 150, 80, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("First Name :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 220, 120, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Password :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 290, 99, 22);

        jLabel_Val_ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Val_ID.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Val_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel_Val_IDKeyReleased(evt);
            }
        });
        jPanel1.add(jLabel_Val_ID);
        jLabel_Val_ID.setBounds(170, 180, 250, 30);

        jTextField_Fname.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jTextField_Fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_FnameKeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_Fname);
        jTextField_Fname.setBounds(170, 210, 250, 30);

        jLabel_Val_FName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Val_FName.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_FName);
        jLabel_Val_FName.setBounds(170, 250, 250, 30);

        jPasswordField_Password.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPasswordField_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField_PasswordKeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordField_Password);
        jPasswordField_Password.setBounds(170, 290, 250, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("V");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(420, 140, 20, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Last Name :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(440, 210, 120, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Re-Type Password :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(440, 290, 190, 30);

        jTextField_Lname1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jTextField_Lname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Lname1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_Lname1);
        jTextField_Lname1.setBounds(620, 210, 250, 30);

        jPasswordField_Re_Type_Pw.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPasswordField_Re_Type_Pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField_Re_Type_PwKeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordField_Re_Type_Pw);
        jPasswordField_Re_Type_Pw.setBounds(630, 290, 240, 30);

        jButton_Close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Close.setText("Close");
        jButton_Close.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Close);
        jButton_Close.setBounds(720, 390, 120, 40);

        jButton_Clr1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Clr1.setText("Clear");
        jButton_Clr1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_Clr1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Clr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Clr1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Clr1);
        jButton_Clr1.setBounds(500, 390, 120, 40);

        jButton_Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Update.setText("Update");
        jButton_Update.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Update);
        jButton_Update.setBounds(280, 390, 120, 40);

        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Back.setText("<<Back");
        jButton_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jButton_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back);
        jButton_Back.setBounds(50, 390, 120, 40);

        jLabel_Val_Password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Val_Password.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_Password);
        jLabel_Val_Password.setBounds(170, 330, 250, 30);

        jLabel_Val_Retype_Psswd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Val_Retype_Psswd.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_Retype_Psswd);
        jLabel_Val_Retype_Psswd.setBounds(630, 330, 240, 30);

        jLabel_Val_LName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Val_LName.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_LName);
        jLabel_Val_LName.setBounds(620, 250, 250, 30);

        jLabel_Show_Password_dont_Delete.setText("jLabel3");
        jPanel1.add(jLabel_Show_Password_dont_Delete);
        jLabel_Show_Password_dont_Delete.setBounds(50, 330, 0, 14);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_IDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDKeyReleased
        jLabel_Val_ID.setText("");
    }//GEN-LAST:event_jTextField_IDKeyReleased

    private void jTextField_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDKeyTyped
        
        char c = evt.getKeyChar();
        
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTextField_IDKeyTyped

    private void jLabel_Val_IDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel_Val_IDKeyReleased
        char c = evt.getKeyChar();
        
        if ((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            
            jLabel_Val_ID.setText("");
        }
    }//GEN-LAST:event_jLabel_Val_IDKeyReleased

    private void jTextField_FnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FnameKeyReleased
        jLabel_Val_FName.setText("");
    }//GEN-LAST:event_jTextField_FnameKeyReleased

    private void jPasswordField_PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordKeyReleased
        jLabel_Val_Password.setText("");
    }//GEN-LAST:event_jPasswordField_PasswordKeyReleased

    private void jLabel_Ico_SHOW_PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Ico_SHOW_PasswordMouseClicked
        
        if (jLabel_Show_Password_dont_Delete.getText().equals("")) {
            
            jPasswordField_Password.setEchoChar((char) 0);
            jLabel_Show_Password_dont_Delete.setText("set");
            
        } else {
            
            jPasswordField_Password.setEchoChar('*');
            jLabel_Show_Password_dont_Delete.setText("");
            
        }
    }//GEN-LAST:event_jLabel_Ico_SHOW_PasswordMouseClicked

    private void jLabel_Ico_SHOW_PasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Ico_SHOW_PasswordMouseEntered
        
        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153, 153, 153));
        jLabel_Ico_SHOW_Password.setBorder(Lable__Border);
        jLabel_Ico_SHOW_Password.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLabel_Ico_SHOW_PasswordMouseEntered

    private void jLabel_Ico_SHOW_PasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Ico_SHOW_PasswordMouseExited
        
        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        jLabel_Ico_SHOW_Password.setBorder(Lable__Border);
        jLabel_Ico_SHOW_Password.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_Ico_SHOW_PasswordMouseExited

    private void jTextField_Lname1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Lname1KeyReleased
        jLabel_Val_LName.setText(null);
    }//GEN-LAST:event_jTextField_Lname1KeyReleased

    private void jPasswordField_Re_Type_PwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_Re_Type_PwKeyReleased
        jLabel_Val_Retype_Psswd.setText("");
    }//GEN-LAST:event_jPasswordField_Re_Type_PwKeyReleased

    private void jLabel_Ico_SHOW_Retype_PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Ico_SHOW_Retype_PasswordMouseClicked
        
        if (jLabel_Show_Password_dont_Delete.getText().equals("")) {
            
            jPasswordField_Re_Type_Pw.setEchoChar((char) 0);
            jLabel_Show_Password_dont_Delete.setText("set");
            
        } else {
            
            jPasswordField_Re_Type_Pw.setEchoChar('*');
            jLabel_Show_Password_dont_Delete.setText("");
            
        }
    }//GEN-LAST:event_jLabel_Ico_SHOW_Retype_PasswordMouseClicked

    private void jLabel_Ico_SHOW_Retype_PasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Ico_SHOW_Retype_PasswordMouseEntered
        
        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153, 153, 153));
        jLabel_Ico_SHOW_Password.setBorder(Lable__Border);
        jLabel_Ico_SHOW_Password.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLabel_Ico_SHOW_Retype_PasswordMouseEntered

    private void jLabel_Ico_SHOW_Retype_PasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Ico_SHOW_Retype_PasswordMouseExited
        
        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        jLabel_Ico_SHOW_Password.setBorder(Lable__Border);
        jLabel_Ico_SHOW_Password.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_Ico_SHOW_Retype_PasswordMouseExited

    private void jButton_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CloseActionPerformed
        
        int a;
        
        getToolkit().beep();
        a = JOptionPane.showConfirmDialog(null, "Are you sure to extit the program?", "Close the program?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (a == 0) {
            
            this.dispose();
        }
    }//GEN-LAST:event_jButton_CloseActionPerformed

    private void jButton_Clr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Clr1ActionPerformed
        
        int a;
        
        a = JOptionPane.showConfirmDialog(null, "Are you sure to you went to clear the data", "Clear Data", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (a == 0) {
            
            jLabel_Val_FName.setText(null);
            jLabel_Val_ID.setText(null);
            jLabel_Val_Password.setText(null);
            jLabel_Val_Retype_Psswd.setText(null);
            jTextField_Fname.setText(null);
            jTextField_ID.setText(null);
            jPasswordField_Password.setText(null);
            jPasswordField_Re_Type_Pw.setText(null);
            jTextField_Lname1.setText(null);
            jLabel_Val_LName.setText(null);
            jTextField_ID.grabFocus();
            
        }
    }//GEN-LAST:event_jButton_Clr1ActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        
        if (jTextField_Fname.getText().trim().isEmpty() && jTextField_ID.getText().trim().isEmpty() && jPasswordField_Password.getText().trim().isEmpty() && jPasswordField_Re_Type_Pw.getText().trim().isEmpty() && jTextField_Lname1.getText().trim().isEmpty()) {
            
            jLabel_Val_FName.setText("Enter your first name.");
            jLabel_Val_ID.setText("N.I.C Number is empty.");
            jLabel_Val_Password.setText("Password is empty.");
            jLabel_Val_Retype_Psswd.setText("Re-Typed password is empty.");
            jLabel_Val_LName.setText("Enter your Last Name.");
            
        } else if (jTextField_Fname.getText().trim().isEmpty()) {
            
            jLabel_Val_FName.setText("Enter your first name.");
            
        } else if (jTextField_ID.getText().trim().isEmpty()) {
            
            jLabel_Val_ID.setText("N.I.C Number is empty.");
            
        } else if (jPasswordField_Re_Type_Pw.getText().trim().isEmpty()) {
            
            jLabel_Val_Retype_Psswd.setText("Re-Typed password is empty.");
            
        } else if (jPasswordField_Password.getText().trim().isEmpty()) {
            
            jLabel_Val_Password.setText("Password is empty.");
            
        } else if (jTextField_Lname1.getText().trim().isEmpty()) {
            
            jLabel_Val_LName.setText("Enter your last name.");
            
        } else if (!jPasswordField_Password.getText().equals(jPasswordField_Re_Type_Pw.getText())) {
            
            JOptionPane.showMessageDialog(null, "Password is not matched", "Messege", JOptionPane.WARNING_MESSAGE);
            
            jLabel_Val_FName.setText(null);
            jLabel_Val_ID.setText(null);
            jLabel_Val_Password.setText(null);
            jLabel_Val_Retype_Psswd.setText(null);
            jTextField_Fname.setText(null);
            jTextField_ID.setText(null);
            jPasswordField_Password.setText(null);
            jPasswordField_Re_Type_Pw.setText(null);
            jTextField_Lname1.setText(null);
            jLabel_Val_LName.setText(null);
            jTextField_ID.grabFocus();
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Password is matched");
            
            try {
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "inventry_management_system";
                String user = "root";
                String pword = "123456";
                
                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);
                
                String query = "UPDATE user SET Password=? ,Re_Enter_Password=? ,First_Name=? ,Last_Name=? WHERE ID=?"; 
                
                PreparedStatement pst = con.prepareStatement(query);
                
                pst.setString(5, jTextField_ID.getText());//query eke adala feild eka yedi athi place eke number eka merhanadi parameeeter eka lesa yediya yuthuya.
                pst.setString(1, jPasswordField_Password.getText());
                pst.setString(2, jPasswordField_Re_Type_Pw.getText());
                pst.setString(3, jTextField_Fname.getText());
                pst.setString(4, jTextField_Lname1.getText());
                
                pst.executeUpdate();
                
                System.out.println(pst);
                System.out.println("1 row affected");
                
                JOptionPane.showMessageDialog(null, "Your record are updated Succsessfully!!!");
                
                con.close();
                
            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
                
                Logger.getLogger(JFrame_4.class.getName()).log(Level.SEVERE, null, ex);
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, ex);
                
            }
            
            jLabel_Val_FName.setText(null);
            jLabel_Val_ID.setText(null);
            jLabel_Val_Password.setText(null);
            jLabel_Val_Retype_Psswd.setText(null);
            jTextField_Fname.setText(null);
            jTextField_ID.setText(null);
            jPasswordField_Password.setText(null);
            jPasswordField_Re_Type_Pw.setText(null);
            jTextField_Lname1.setText(null);
            jLabel_Val_LName.setText(null);
            jTextField_ID.grabFocus();
            
        }
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        JFrame_6 f6 = new JFrame_6();
        f6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Close;
    private javax.swing.JButton jButton_Clr1;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Ico_SHOW_Password;
    private javax.swing.JLabel jLabel_Ico_SHOW_Retype_Password;
    private javax.swing.JLabel jLabel_Show_Password_dont_Delete;
    private javax.swing.JLabel jLabel_Val_FName;
    private javax.swing.JLabel jLabel_Val_ID;
    private javax.swing.JLabel jLabel_Val_LName;
    private javax.swing.JLabel jLabel_Val_Password;
    private javax.swing.JLabel jLabel_Val_Retype_Psswd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JPasswordField jPasswordField_Re_Type_Pw;
    private javax.swing.JTextField jTextField_Fname;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Lname1;
    // End of variables declaration//GEN-END:variables
}
